# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faa88cb6982d2fe04a7e9708375a396cce53d0f618543a34f5221e1dea22eac090e9b1b05bcc582ded74f2c15c9550073b90b158f254c478a2dd303d3ee4d303

test:
  secret_key_base: 4605b013b428b366b7001bf95e6553719acc302dbf5cec43c68fe00ef4036aa444ea67e15612a3471fbdfe2b79f0251c95ddba8f44ab9e5a12a69964daccde33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
